import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google"
import { CartProvider } from "./context/context";
const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  style: ["normal"],
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "StarBucks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
